### PR TITLE
set reasonable defaults for variables

### PR DESCRIPTION
**Pull request by afeld**

### CODE REVIEW

**Review by Vermyndax — COMMENTED** [review]
@afeld What's the thinking behind removing the meat of the variables in terraform.tfvars.example?

**Comment by afeld** [comment]
@Vermyndax The thinking is that users of the module shouldn't have to set any of those values in most cases. Therefore, only left the required variables in the `.tfvars` file.

**Comment by Vermyndax** [comment]
Hmmm. I'm not so sure we'd want to provide defaults for CIDR ranges, IAM roles, etc. without having a stronger hint that they really should change those values. If people cherry pick this infrastructure and use it directly or as a module, then expect to employ VPC peering with other DevSecOps or infrastructures within GSA, they will run afoul of overlapping CIDR ranges and, (less possible) conflicting names if it's deployed in a multi-purposed AWS account.

**Comment by afeld** [comment]
> expect to employ VPC peering with other DevSecOps or infrastructures within GSA

Sounds like that's still [an open question](https://trello.com/c/PGaNfz1a/114-evaluate-vpc-peering-vs-vpn-model), yeah?

**Comment by afeld** [comment]
It's probably out of the scope of this pull request, but for resources whose `name`s need to be unique in an AWS account, what do you think about including a [random](https://www.terraform.io/docs/providers/random/index.html) value or the [workspace](https://www.terraform.io/docs/state/workspaces.html#current-workspace-interpolation) in the string?

**Comment by afeld** [comment]
Also, if we want to wait on the VPC peering/VPN conversation, I'm happy to back out those changes.

**Comment by afeld** [comment]
Thinking more about this, I think I'd rather err on the side of having too many defaults rather than too few. The more variables the user is required to set, the greater the barrier to entry.

**Comment by afeld** [comment]
...also makes things like Continuous Integration setup for this repository easier 😁

**Review by Vermyndax — APPROVED** [review]

**Pull request merged**
